export type MenuCategory =
  | 'appetizers'
  | 'chicken'
  | 'handhelds'
  | 'specialty'
  | 'seafood'
  | 'soups'
  | 'chifa'
  | 'shareables'
  | 'desserts'
  | 'drinks';

export type MenuItem = {
  id: string;
  name: string;
  description: string;
  price: string;
  category: MenuCategory;
  popular?: boolean;
  spicy?: boolean;
  note?: string;
};

export const menuItems: MenuItem[] = [
  // APPETIZERS
  {
    id: 'papa-rellena',
    name: 'Papa Rellena',
    description: 'A golden, crispy potato filled with seasoned ground beef, onions, olives, and boiled egg, served with our house salsa criolla.',
    price: '$12.00',
    category: 'appetizers',
    note: 'Cooked to order',
  },
  {
    id: 'salchipapa',
    name: 'Salchipapa',
    description: 'Thinly sliced, pan fried all beef hot dogs tossed with french fries. Served with ketchup, mayonnaise and mustard.',
    price: '$11.00',
    category: 'appetizers',
    note: 'Cooked to order',
  },
  {
    id: 'yuca-frita',
    name: 'Yuca Frita',
    description: 'Pieces of boiled yucca, fried to perfection and served with huancaina sauce.',
    price: '$10.00',
    category: 'appetizers',
    note: 'Cooked to order',
  },
  {
    id: 'papa-huancaina',
    name: 'Papa a la Huancaina',
    description: 'Thick slices of steamed potatoes topped with huancaina sauce made with fresh cheese and aji peppers, garnished with eggs and cheese.',
    price: '$10.00',
    category: 'appetizers',
  },
  {
    id: 'causa-pollo',
    name: 'Causa de Pollo',
    description: 'Whipped yellow potato cakes flavored with peruvian yellow pepper and served with peruvian styled chicken salad.',
    price: '$12.50',
    category: 'appetizers',
    popular: true,
  },
  {
    id: 'tamal',
    name: 'Tamal de Pollo o Chancho',
    description: 'Mashed corn wrapped in a plantain leaf, filled with strips of chicken or pork.',
    price: '$11.00',
    category: 'appetizers',
    note: 'Ask for availability',
  },
  {
    id: 'chicharron-carretillero',
    name: 'Chicharron Carretillero',
    description: 'Boneless chunks of pork meat fried to a perfect golden and crispy texture. Served with yucca and our signature creole salsa.',
    price: '$15.00',
    category: 'appetizers',
    note: 'Cooked to order',
  },
  {
    id: 'chicken-wings',
    name: "Taty's Signature Chicken Wings",
    description: 'Wings tossed in your choice of sauce: Buffalo, Lemon Pepper, Mambo, Old Bay, or Hot Honey.',
    price: '$13.00',
    category: 'appetizers',
    popular: true,
    note: 'Cooked to order',
  },

  // CHARCOAL CHICKEN (Pollo a la Brasa) + FRIED CHICKEN
  {
    id: 'quarter-chicken',
    name: 'Quarter Chicken (Pollo a la Brasa)',
    description: 'White or dark meat. Served with two medium sides.',
    price: '$12.00',
    category: 'chicken',
    popular: true,
  },
  {
    id: 'half-chicken',
    name: 'Half Chicken (Pollo a la Brasa)',
    description: 'White & dark meat. Served with two medium sides.',
    price: '$16.00',
    category: 'chicken',
    popular: true,
  },
  {
    id: 'whole-chicken',
    name: 'Whole Chicken (Pollo a la Brasa)',
    description: 'Whole charcoal chicken with two large sides. Only white meat +$3, only dark meat +$2.',
    price: '$27.00',
    category: 'chicken',
  },
  {
    id: '2pc-fried-chicken',
    name: '2pc Fried Chicken',
    description: 'Two pieces of crispy fried chicken with two medium sides.',
    price: '$14.50',
    category: 'chicken',
    note: 'Cooked to order',
  },
  {
    id: '4pc-fried-chicken',
    name: '4pc Fried Chicken',
    description: 'Four pieces of crispy fried chicken with two medium sides.',
    price: '$16.50',
    category: 'chicken',
  },
  {
    id: 'broaster-wings',
    name: '3pc Crispy Broaster Wings',
    description: 'Three crispy broaster wings served with french fries.',
    price: '$13.50',
    category: 'chicken',
  },

  // HANDHELDS
  {
    id: 'butifarra',
    name: 'Butifarra Sandwich',
    description: 'A Peruvian classic. A butifarra is filled with sliced savory jamon del pais, peruvian country-style seasoned ham, with onions and creole sauce.',
    price: '$13.00',
    category: 'handhelds',
    note: 'Cooked to order',
  },
  {
    id: 'pan-con-chicharron',
    name: 'Porky Sandwich',
    description: 'Pan con chicharron is a Peruvian-style pork belly sandwich with creole salsa, fried sweet potatoes, and pork belly.',
    price: '$13.00',
    category: 'handhelds',
    popular: true,
    note: 'Cooked to order',
  },
  {
    id: 'lomo-saltado-sandwich',
    name: 'Lomo Saltado Sandwich',
    description: 'Tender strips of juicy beef tenderloin, sautéed with onions, tomatoes, and bold spices on a freshly baked bread, topped with a drizzle of savory sauce.',
    price: '$13.00',
    category: 'handhelds',
    note: 'Cooked to order',
  },
  {
    id: 'royal-burger',
    name: 'Royal Burger',
    description: 'Our Peruvian style burger made with ham, bacon, cheese and fried egg.',
    price: '$13.00',
    category: 'handhelds',
    note: 'Cooked to order',
  },
  {
    id: 'street-burger',
    name: 'Street Burger',
    description: 'A homemade beef patty, fried hot dog slices, thinly sliced homemade potato chips, and our secret sauce.',
    price: '$13.00',
    category: 'handhelds',
    note: 'Cooked to order',
  },
  {
    id: 'hot-crispy-sandwich',
    name: "Taty's Hot Crispy Chicken Sandwich",
    description: '3 Peruvian chilis, house mayonnaise, lettuce, and tomato. Comes with french fries.',
    price: '$12.90',
    category: 'handhelds',
    spicy: true,
    note: 'Cooked to order',
  },
  {
    id: 'buffalo-ranch-sandwich',
    name: 'Buffalo Ranch Crispy Sandwich',
    description: 'Creamy buffalo sauce, house mayonnaise, lettuce, and tomato. Comes with french fries.',
    price: '$12.90',
    category: 'handhelds',
    note: 'Cooked to order',
  },
  {
    id: 'mambo-sandwich',
    name: 'Mambo Crispy Chicken Sandwich',
    description: 'Mambo sauce, house mayonnaise, lettuce, and tomato. Comes with french fries.',
    price: '$12.90',
    category: 'handhelds',
    note: 'Cooked to order',
  },
  {
    id: 'hot-honey-sandwich',
    name: 'Hot Honey Crispy Chicken Sandwich',
    description: 'Hot honey sauce, house mayonnaise, lettuce, and tomato. Comes with french fries.',
    price: '$12.90',
    category: 'handhelds',
    note: 'Cooked to order',
  },
  {
    id: 'brasa-sandwich',
    name: 'The Brasa Chicken Sandwich',
    description: 'Pulled charcoal chicken, celery, house mayonnaise, lettuce, and tomato. Comes with french fries.',
    price: '$12.90',
    category: 'handhelds',
    popular: true,
    note: 'Cooked to order',
  },
  {
    id: 'tatys-chicken-sandwich',
    name: "Taty's Chicken Sandwich",
    description: 'Crispy chicken, cole slaw, banana peppers, and secret sauce. Comes with french fries.',
    price: '$12.90',
    category: 'handhelds',
    note: 'Cooked to order',
  },
  {
    id: 'chicken-wrap',
    name: "Taty's Chicken Wrap",
    description: 'Beans, rice, yellow sauce, pulled charcoal chicken, and plantain.',
    price: '$12.90',
    category: 'handhelds',
    note: 'Cooked to order',
  },
  {
    id: 'philly-cheese',
    name: "Taty's Chicken Philly Cheese Sandwich",
    description: 'Chicken, onions, green peppers, lettuce, tomato, mayo, and fries.',
    price: '$12.90',
    category: 'handhelds',
    note: 'Cooked to order',
  },

  // SPECIALTY ENTREES
  {
    id: 'lomo-saltado',
    name: 'Lomo Saltado',
    description: 'Tender slices of deeply seared beef, blister-y onions, juicy tomatoes, and crispy french-fried potatoes in this classic chinese-peruvian stir-fry.',
    price: '$23.00',
    category: 'specialty',
    popular: true,
    note: 'Cooked to order',
  },
  {
    id: 'seco-cordero',
    name: 'Seco de Cordero',
    description: 'Juicy lamb shank braised in cilantro stew served with creamy canary beans and white rice.',
    price: '$25.00',
    category: 'specialty',
    note: 'Cooked to order',
  },
  {
    id: 'tallarines-verdes',
    name: 'Tallarines Verdes con Bisteck',
    description: 'Peruvian style linguini al dente coated with a warm pesto sauce topped with breadred tender steak.',
    price: '$20.00',
    category: 'specialty',
    note: 'Cooked to order',
  },
  {
    id: 'churrasco',
    name: 'Churrasco a lo Pobre',
    description: 'Skirt steak poor style. Skirt steak with egg, rice, sweet plantains, and fries — an unexpected combination you should try!',
    price: '$23.00',
    category: 'specialty',
    note: 'Cooked to order',
  },
  {
    id: 'tallarin-saltado',
    name: 'Tallarin Saltado',
    description: 'Peruvian stir fried chicken and noodle dish that uses local South American ingredients combined with Asian influence. Add beef or shrimp +$5.',
    price: '$20.00',
    category: 'specialty',
    note: 'Cooked to order',
  },
  {
    id: 'arroz-con-pollo',
    name: 'Arroz con Pollo',
    description: 'Traditional Peruvian cilantro rice served with a piece of chicken, paired with creamy Huancaina. Add ceviche +$10.',
    price: '$25.00',
    category: 'specialty',
    popular: true,
  },
  {
    id: 'aji-de-gallina',
    name: 'Aji de Gallina',
    description: 'Shredded chicken in a creamy and spicy sauce of yellow chilli peppers, pecans and cheese. Served with rice, potatoes, eggs, and olives.',
    price: '$21.00',
    category: 'specialty',
    spicy: true,
    note: 'Cooked to order',
  },
  {
    id: 'tallarines-huancaina-lomo',
    name: 'Tallarines a la Huancaina con Lomo',
    description: 'Linguini in a creamy huancaina sauce (made with peruvian yellow pepper and fresh cheese) served with Lomo saltado.',
    price: '$23.00',
    category: 'specialty',
    note: 'Cooked to order',
  },
  {
    id: 'arroz-chaufa',
    name: 'Arroz Chaufa',
    description: 'Asian inspired chicken fried rice dish made from a variety of fresh aromatic ingredients and asian spices. Add beef or shrimp +$5.',
    price: '$16.00',
    category: 'specialty',
    note: 'Cooked to order',
  },
  {
    id: 'anticucho',
    name: 'Anticucho',
    description: 'Marinated chunks of beef heart skewered and served with peruvian corn and grilled potatoes. Add grilled tripe +$5.',
    price: '$17.00',
    category: 'specialty',
    note: 'Cooked to order',
  },
  {
    id: 'tacu-tacu-pobre',
    name: 'Tacu Tacu a lo Pobre',
    description: 'Juicy tender steak topped with fried egg, served with fried plantains and large fried quenelle cake made with rice and canary beans.',
    price: '$25.00',
    category: 'specialty',
    note: 'Cooked to order',
  },
  {
    id: 'tacu-tacu-mariscos',
    name: 'Tacu Tacu en Salsa de Mariscos',
    description: 'Tacu tacu with seafood peruvian style.',
    price: '$25.00',
    category: 'specialty',
    note: 'Cooked to order',
  },
  {
    id: 'tacu-tacu-lomo',
    name: 'Tacu Tacu a lo Pobre con Lomo Saltado',
    description: 'Tacu tacu with our authentic lomo saltado.',
    price: '$25.00',
    category: 'specialty',
    note: 'Cooked to order',
  },

  // SEAFOOD
  {
    id: 'ceviche-pescado',
    name: 'Ceviche de Pescado',
    description: 'Fresh fish marinated in lime juice, peruvian spices and herbs, served with glazed sweet potato, peruvian corn and dried crunchy corn kernels.',
    price: '$22.00',
    category: 'seafood',
    popular: true,
    note: 'Cooked to order',
  },
  {
    id: 'ceviche-mixto',
    name: 'Ceviche Mixto',
    description: 'Fresh fish, mussels, calamari and shrimp marinated in lime juice, peruvian spices and herbs, served with glazed sweet potato, corn on the cob and dried crunchy corn kernels.',
    price: '$28.00',
    category: 'seafood',
    note: 'Cooked to order',
  },
  {
    id: 'leche-tigre',
    name: 'Leche de Tigre',
    description: 'Lime juice, sliced onions, chillies, salt and pepper with a bit of fish and shrimp juice served in a glass. A hangover cure as well as an aphrodisiac!',
    price: '$15.00',
    category: 'seafood',
    note: 'Cooked to order',
  },
  {
    id: 'duo-marino',
    name: 'Duo Marino',
    description: 'Seafood rice and ceviche accompanied with corn, sweet potato, and tartar sauce.',
    price: '$24.00',
    category: 'seafood',
    note: 'Cooked to order',
  },
  {
    id: 'trio-marino',
    name: 'Trio Marino',
    description: 'Seafood rice, deep fried fish, and ceviche accompanied with corn, sweet potato, and tartar sauce.',
    price: '$28.00',
    category: 'seafood',
    note: 'Cooked to order',
  },
  {
    id: 'arroz-mariscos',
    name: 'Arroz con Mariscos',
    description: 'Peruvian style paella. A creamy yellow pepper sauce mixed with shrimp, calamari, mussels, red peppers, and aromatic cilantro.',
    price: '$25.00',
    category: 'seafood',
    popular: true,
    note: 'Cooked to order',
  },
  {
    id: 'causa-acevichada',
    name: 'Causa Acevichada',
    description: 'Mashed potato cake flavored with aji amarillo, with a filling of fresh avocado, mayonnaise, and topped with our traditional ceviche.',
    price: '$23.00',
    category: 'seafood',
    note: 'Cooked to order',
  },
  {
    id: 'chicharron-pescado',
    name: 'Chicharron de Pescado',
    description: 'Deep fried fish chunks served with onion salad and fried yucca.',
    price: '$19.00',
    category: 'seafood',
    note: 'Cooked to order',
  },
  {
    id: 'chicharron-calamar',
    name: 'Chicharron de Calamar',
    description: 'Seasoned calamari deep fried to a golden brown, served with fried yucca or fries and our signature sauce.',
    price: '$20.00',
    category: 'seafood',
    note: 'Cooked to order',
  },
  {
    id: 'jalea-mixta',
    name: 'Jalea Mixta',
    description: 'A combination of fried seafood including shrimp, calamari, bay scallops and fish chunks served with onion salad and fried yucca.',
    price: '$26.00',
    category: 'seafood',
    note: 'Cooked to order',
  },
  {
    id: 'pescado-macho',
    name: 'Pescado a lo Macho',
    description: 'Fried fresh fillet topped with a juicy blend of seafood and our special sauce, served with rice and crispy potatoes.',
    price: '$24.00',
    category: 'seafood',
    note: 'Cooked to order',
  },

  // SOUPS
  {
    id: 'parihuela',
    name: 'Parihuela',
    description: 'The most traditional coastal soup from Peru. A perfect combination of the freshest seafood and peruvian spices and herbs — fish consommé served with crab legs, mussels, squid, clams and shrimp.',
    price: '$22.00',
    category: 'soups',
    popular: true,
    note: 'Cooked to order',
  },
  {
    id: 'sudado-pescado',
    name: 'Sudado de Pescado',
    description: 'Steamed fish cooked in fish stock base, onions, aji amarillo, panca peppers. Served with a side of white rice.',
    price: '$22.00',
    category: 'soups',
    note: 'Cooked to order',
  },
  {
    id: 'chupe-camarones',
    name: 'Chupe de Camarones',
    description: 'Fresh shrimp cooked in a creamy broth with rice potato, peas, corn, cheese, milk, and topped with a perfect poached egg and herbs.',
    price: '$22.00',
    category: 'soups',
    note: 'Cooked to order',
  },
  {
    id: 'caldo-gallina',
    name: 'Caldo de Gallina',
    description: 'A rich and comforting soup with tender hen, noodles, potatoes, and a boiled egg in a flavorful broth. An authentic taste of Peru! Add Gallina acevichada +$2.',
    price: '$17.00',
    category: 'soups',
    note: 'Ask for availability',
  },

  // PERUVIAN CHINESE STYLE "CHIFA"
  {
    id: 'aeropuerto',
    name: 'Aeropuerto',
    description: 'A chifa (Peruvian Chinese) dish made of arroz chaufa where a small portion of noodles are added and mixed at the end of the cooking process resulting in a fried dish with noodles.',
    price: '$18.00',
    category: 'chifa',
    note: 'Cooked to order',
  },
  {
    id: 'sopa-wonton',
    name: 'Sopa Wonton Especial',
    description: 'Peruvian style wonton soup with pork, shrimp and chicken.',
    price: '$16.00',
    category: 'chifa',
    note: 'Cooked to order',
  },
  {
    id: 'tallarin-oriental',
    name: 'Tallarin Saltado Oriental',
    description: 'Peruvian style stir fried noodles.',
    price: '$18.00',
    category: 'chifa',
    note: 'Cooked to order',
  },
  {
    id: 'kam-lu-wantan',
    name: 'Kam Lu Wantan',
    description: 'Peruvian-Chinese stir-fry with crispy wontons, chicken, pork, shrimp, veggies, pineapple, and peach in a sweet-savory sauce.',
    price: '$22.00',
    category: 'chifa',
    popular: true,
    note: 'Cooked to order',
  },
  {
    id: 'navo-encurtido',
    name: 'Navo Encurtido',
    description: 'Pickled turnip, a classic Peruvian-Chinese side.',
    price: 'Small $3 / Large $5',
    category: 'chifa',
  },

  // SHAREABLES
  {
    id: 'fiesta-marina',
    name: 'Fiesta Marina',
    description: 'Ceviche de Pescado, Arroz con Mariscos, Chicharron de Pescado, Causa de Langostino, Leche de Tigre.',
    price: '$49.90',
    category: 'shareables',
    note: 'Cooked to order',
  },
  {
    id: 'parrillada-tatys',
    name: "Parrillada Taty's",
    description: 'Chuleta de Cerdo, Bisteck de Res, 1/4 de Pollo a la Brasa, 1 Chorizo, 1 Palo de Anticucho, Porcion de Papas, Porcion de Choclo.',
    price: '$49.90',
    category: 'shareables',
    note: 'Cooked to order',
  },
  {
    id: 'desayuno-lurin',
    name: 'Desayuno Lurin',
    description: 'Chicharron, Porcion de Camote, Tamal de Pollo o Chancho, Sarza Criolla, Salchicha Huachana, Pan.',
    price: '$25.00',
    category: 'shareables',
    note: 'Cooked to order',
  },
  {
    id: 'tatys-broaster',
    name: "Taty's Broaster",
    description: 'Eight crispy fried chicken pieces served with fries, a hot dog, fresh salad, and a variety of sauces.',
    price: '$30.00',
    category: 'shareables',
    popular: true,
    note: 'Cooked to order',
  },
  {
    id: 'jalea-galactica',
    name: 'Jalea Galáctica',
    description: '2 Whole Fish, 2 Fish Fillets, Fried Fish Chicharron, Mixed Seafood, Fried Yuca, Criolla Sauce.',
    price: '$59.90',
    category: 'shareables',
    note: 'Cooked to order',
  },
  {
    id: 'ceviche-galactico',
    name: 'Ceviche Galáctico',
    description: 'Fresh Fish Ceviche, Mixed Seafood, Crispy Calamari, Fried Yuca, Cancha (Peruvian Corn Nuts), Sweet Potato.',
    price: '$59.90',
    category: 'shareables',
    note: 'Cooked to order',
  },

  // DESSERTS
  {
    id: 'tres-leches',
    name: 'Tres Leches',
    description: 'Classic Peruvian tres leches cake soaked in three kinds of milk.',
    price: '$9.00',
    category: 'desserts',
    popular: true,
  },
  {
    id: 'torta-chocolate',
    name: 'Torta de Chocolate',
    description: 'Rich and decadent chocolate cake.',
    price: '$8.50',
    category: 'desserts',
  },
  {
    id: 'crema-volteada',
    name: 'Crema Volteada',
    description: 'Peruvian style flan, smooth and creamy with caramel.',
    price: '$6.00',
    category: 'desserts',
  },
  {
    id: 'chocoflan',
    name: 'Chocoflan',
    description: 'The perfect combination of chocolate cake and flan in one dessert.',
    price: '$8.00',
    category: 'desserts',
  },
  {
    id: 'alfajores',
    name: 'Alfajores',
    description: 'Traditional Peruvian sandwich cookies filled with dulce de leche.',
    price: '$6.00',
    category: 'desserts',
  },
  {
    id: 'cuchareable',
    name: 'Cuchareable',
    description: 'Ask for today\'s flavor.',
    price: '$9.00',
    category: 'desserts',
  },

  // DRINKS
  {
    id: 'house-drinks',
    name: 'Fresh From the House',
    description: 'Chicha Morada, Maracuya, or Horchata.',
    price: '$4.00',
    category: 'drinks',
    popular: true,
  },
  {
    id: 'lemonade',
    name: 'Lemonade',
    description: 'Mango, peach, pineapple, passion fruit, or strawberry.',
    price: '$4.00',
    category: 'drinks',
  },
  {
    id: 'can-soda',
    name: 'Can Soda',
    description: 'Coke products.',
    price: '$2.50',
    category: 'drinks',
  },
  {
    id: 'bottled-soda',
    name: 'Bottled Soda',
    description: 'Coke products.',
    price: '$4.00',
    category: 'drinks',
  },
  {
    id: 'inca-kola',
    name: 'Inca Kola 2 Lts',
    description: 'The golden Peruvian soda.',
    price: '$8.00',
    category: 'drinks',
    popular: true,
  },
];

export const categories: { id: MenuCategory | 'all'; label: string }[] = [
  { id: 'all', label: 'All Items' },
  { id: 'appetizers', label: 'Appetizers' },
  { id: 'chicken', label: 'Chicken' },
  { id: 'handhelds', label: 'Handhelds' },
  { id: 'specialty', label: 'Specialty Plates' },
  { id: 'seafood', label: 'Seafood' },
  { id: 'soups', label: 'Soups' },
  { id: 'chifa', label: 'Chifa' },
  { id: 'shareables', label: 'Shareables' },
  { id: 'desserts', label: 'Desserts' },
  { id: 'drinks', label: 'Drinks' },
];

export const featuredItems = menuItems.filter((item) => item.popular).slice(0, 4);
